name: Dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run:  dotnet restore
      working-directory: ./src/src/WebGentel-BookStore/WebGentel-BookStore.sln
    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./src/src/WebGentel-BookStore/WebGentel-BookStore.sln
    ##- name: Test
    ## run:  dotnet test --no-build --verbosity normal
